const data = [
    {
        id: '1',
        firstName: 'Bob',
        lastName: 'Ly',
        startDate: '21/07/2020',
        department: 'Sales',
        dateOfBirth: '21/07/1968',
        street: 'Main street',
        city: 'Dothan',
        state: 'AL',
        zipCode: 35005
    },
    {
        id: '2',
        firstName: 'Patrick',
        lastName: 'Smith',
        startDate: '21/07/2011',
        department: 'Engineering',
        dateOfBirth: '01/01/1976',
        street: 'Forest street',
        city: 'Los Angeles',
        state: 'CA',
        zipCode: 90011
    },
    {
        id: '3',
        firstName: 'Lisa',
        lastName: 'Stark',
        startDate: '21/07/2000',
        department: 'Legal',
        dateOfBirth: '19/12/1973',
        street: 'Summer street',
        city: 'Jacksonville',
        state: 'FL',
        zipCode: 32004
    },
    {
        id: '4',
        firstName: 'Jean',
        lastName: 'Dupont',
        startDate: '21/07/2005',
        department: 'Marketing',
        dateOfBirth: '07/09/1982',
        street: 'Madison avenue',
        city: 'Indianapolis',
        state: 'IN',
        zipCode: 47906
    },
    {
        id: '5',
        firstName: 'Pierre',
        lastName: 'Dallas',
        startDate: '21/07/2012',
        department: 'Human Resources',
        dateOfBirth: '11/02/1967',
        street: 'Red street',
        city: 'Cambridge',
        state: 'MA',
        zipCode: 2139
    },
    {
        id: '6',
        firstName: 'Luc',
        lastName: 'Diaz',
        startDate: '21/07/2018',
        department: 'Sales',
        dateOfBirth: '28/10/1991',
        street: 'Robert street',
        city: 'Foley',
        state: 'AL',
        zipCode: 36695
    },
    {
        id: '7',
        firstName: 'Pascal',
        lastName: 'Bush',
        startDate: '21/07/2007',
        department: 'Engineering',
        dateOfBirth: '17/05/1966',
        street: 'Apache street',
        city: 'San Diego',
        state: 'CA',
        zipCode: 90011
    },
    {
        id: '8',
        firstName: 'Brigitte',
        lastName: 'Amazon',
        startDate: '21/07/2019',
        department: 'Legal',
        dateOfBirth: '10/11/1985',
        street: 'Trinity street',
        city: 'Miami',
        state: 'FL',
        zipCode: 32007
    },
    {
        id: '9',
        firstName: 'George',
        lastName: 'Tiger',
        startDate: '21/07/2004',
        department: 'Marketing',
        dateOfBirth: '04/01/1990',
        street: 'Tower street',
        city: 'Evansville',
        state: 'IN',
        zipCode: 46307
    },
    {
        id: '10',
        firstName: 'Jeanne',
        lastName: 'Wood',
        startDate: '21/07/2020',
        department: 'Human Resources',
        dateOfBirth: '13/08/1978',
        street: 'Ridge street',
        city: 'Boston',
        state: 'MA',
        zipCode: 2127
    },
    {
        id: '11',
        firstName: 'Jenny',
        lastName: 'Craig',
        startDate: '01/01/2000',
        department: 'Sales',
        dateOfBirth: '15/06/1960',
        street: 'Grey street',
        city: 'Phoenix',
        state: 'AR',
        zipCode: 85364
    },
    {
        id: '12',
        firstName: 'Elizabeth',
        lastName: 'Ronald',
        startDate: '20/05/2019',
        department: 'Engineering',
        dateOfBirth: '21/11/1971',
        street: 'Spring street',
        city: 'Denver',
        state: 'CO',
        zipCode: 80014
    },
    {
        id: '13',
        firstName: 'Louis',
        lastName: 'Martinez',
        startDate: '07/09/2020',
        department: 'Legal',
        dateOfBirth: '04/12/1980',
        street: 'Sunset street',
        city: 'Atlanta',
        state: 'GE',
        zipCode: 30043
    },
    {
        id: '14',
        firstName: 'Mirelle',
        lastName: 'Bertrand',
        startDate: '31/01/2001',
        department: 'Marketing',
        dateOfBirth: '29/08/1980',
        street: 'Beach avenue',
        city: 'Kahului',
        state: 'HA',
        zipCode: 96733
    },
    {
        id: '15',
        firstName: 'Josh',
        lastName: 'Pringles',
        startDate: '01/09/2012',
        department: 'Human Resources',
        dateOfBirth: '18/07/1961',
        street: 'Robert street',
        city: 'Oldham',
        state: 'KE',
        zipCode: 40026
    },
    {
        id: '16',
        firstName: 'Victor',
        lastName: 'Chancelor',
        startDate: '15/03/2002',
        department: 'Sales',
        dateOfBirth: '10/12/1981',
        street: 'Nill street',
        city: 'Mandeville',
        state: 'LO',
        zipCode: 70726
    },
    {
        id: '17',
        firstName: 'Megan',
        lastName: 'Rosa',
        startDate: '21/02/2000',
        department: 'Engineering',
        dateOfBirth: '22/01/1969',
        street: 'Sweet street',
        city: 'Missoula',
        state: 'MO',
        zipCode: 59901
    },
    {
        id: '18',
        firstName: 'Suzanne',
        lastName: 'Brod',
        startDate: '13/06/2010',
        department: 'Legal',
        dateOfBirth: '17/07/1982',
        street: 'Salmon street',
        city: 'Portland',
        state: 'OR',
        zipCode: 97229
    },
    {
        id: '19',
        firstName: 'Jules',
        lastName: 'Roots',
        startDate: '10/09/2003',
        department: 'Marketing',
        dateOfBirth: '30/02/1989',
        street: 'Legal street',
        city: 'El Paso',
        state: 'TE',
        zipCode: 79938
    },
    {
        id: '20',
        firstName: 'Laura',
        lastName: 'Peace',
        startDate: '21/11/2019',
        department: 'Human Resources',
        dateOfBirth: '21/08/1977',
        street: 'Bridge street',
        city: 'Roanoke',
        state: 'VI',
        zipCode: 24001
    },
    {
        id: '21',
        firstName: 'Bob',
        lastName: 'Ly',
        startDate: '21/07/2020',
        department: 'Sales',
        dateOfBirth: '21/07/1968',
        street: 'Main street',
        city: 'Dothan',
        state: 'AL',
        zipCode: 35005
    },
    {
        id: '22',
        firstName: 'Patrick',
        lastName: 'Smith',
        startDate: '21/07/2011',
        department: 'Engineering',
        dateOfBirth: '01/01/1976',
        street: 'Forest street',
        city: 'Los Angeles',
        state: 'CA',
        zipCode: 90011
    },
    {
        id: '23',
        firstName: 'Lisa',
        lastName: 'Stark',
        startDate: '21/07/2000',
        department: 'Legal',
        dateOfBirth: '19/12/1973',
        street: 'Summer street',
        city: 'Jacksonville',
        state: 'FL',
        zipCode: 32004
    },
    {
        id: '24',
        firstName: 'Jean',
        lastName: 'Dupont',
        startDate: '21/07/2005',
        department: 'Marketing',
        dateOfBirth: '07/09/1982',
        street: 'Madison avenue',
        city: 'Indianapolis',
        state: 'IN',
        zipCode: 47906
    },
    {
        id: '25',
        firstName: 'Pierre',
        lastName: 'Dallas',
        startDate: '21/07/2012',
        department: 'Human Resources',
        dateOfBirth: '11/02/1967',
        street: 'Red street',
        city: 'Cambridge',
        state: 'MA',
        zipCode: 2139
    },
    {
        id: '26',
        firstName: 'Luc',
        lastName: 'Diaz',
        startDate: '21/07/2018',
        department: 'Sales',
        dateOfBirth: '28/10/1991',
        street: 'Robert street',
        city: 'Foley',
        state: 'AL',
        zipCode: 36695
    },
    {
        id: '27',
        firstName: 'Pascal',
        lastName: 'Bush',
        startDate: '21/07/2007',
        department: 'Engineering',
        dateOfBirth: '17/05/1966',
        street: 'Apache street',
        city: 'San Diego',
        state: 'CA',
        zipCode: 90011
    },
    {
        id: '28',
        firstName: 'Brigitte',
        lastName: 'Amazon',
        startDate: '21/07/2019',
        department: 'Legal',
        dateOfBirth: '10/11/1985',
        street: 'Trinity street',
        city: 'Miami',
        state: 'FL',
        zipCode: 32007
    },
    {
        id: '29',
        firstName: 'George',
        lastName: 'Tiger',
        startDate: '21/07/2004',
        department: 'Marketing',
        dateOfBirth: '04/01/1990',
        street: 'Tower street',
        city: 'Evansville',
        state: 'IN',
        zipCode: 46307
    },
    {
        id: '30',
        firstName: 'Jeanne',
        lastName: 'Wood',
        startDate: '21/07/2020',
        department: 'Human Resources',
        dateOfBirth: '13/08/1978',
        street: 'Ridge street',
        city: 'Boston',
        state: 'MA',
        zipCode: 2127
    },
];

const columns = [
    { field: 'firstName', headerName: 'First Name', width: 142 },
    { field: 'lastName', headerName: 'Last Name', width: 142 },
    { field: 'dateOfBirth', headerName: 'Date Of Birth', width: 142 },
    { field: 'startDate', headerName: 'Start Date', width: 142 },
    { field: 'department', headerName: 'Department', width: 142 },
    { field: 'street', headerName: 'Street', width: 142 },
    { field: 'city', headerName: 'City', width: 142 },
    { field: 'state', headerName: 'State', width: 142 },
    { field: 'zipCode', headerName: 'Zip Code', width: 142 },
]

export { data, columns };